language: php

php:
  - 7.2

before_script:
  - composer update --prefer-source --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit --disallow-test-output --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
